@startuml
namespace StoreManager.Services{

    interface IService
    class ArticleService implements IService
    interface IServiceModel
    class ArticleServiceModel implements IServiceModel
    
    ArticleServiceModel --> ArticleService
    note on link #red: forbidden
}
@enduml